### ISSUE TITLE
Bootloop on 512GB Note 9

### ISSUE THREAD

**Issue by cawilliamson** [exynos-linux-stable/crownlte#2]
Hi there!

I have been struggling trying to resolve this issue for a few days now.

I have both a 128GB Note 9 and a 512GB Note 9 which I'm in the process of migrating from/to. The problem I've got is - neither ELS nor any of the kernels based on it (excluding BeastMode) actually boot on my 512GB device.

I follow the following steps:

- Flash latest DevBase based on ARL3 on both devices.
- Flash ELS kernel on both devices.
- Flash latest Magisk (18.0) on both devices.
- The 128GB device boots. The 512GB device "splashloops" (reboots at the splash screen endlessly.)

Identical model, identical config (excl. 6-8GB RAM, 128-512GB storage.)

As stated - if I follow the same steps above but install BeastMode kernel the devices boot right up. It's very strange indeed. I'm just wondering if you have any ideas or pointers on where the issue may be?

**Logs:**

The logs below were taken from TWRP - from the 128GB device after one successful boot, from the 512GB device after 3 unsuccessful boots (splash loops.) As such, they may be useless but it's the best I could do. There are no tombstones generated on the 512GB device since I don't believe the boot process gets far enough to actually create them.

*128GB:*
128GB kmsg (with magisk): https://termbin.com/0gwx
128GB last_kmsg (with magisk): https://termbin.com/6o6z
128GB kmsg (WITHOUT magisk): https://termbin.com/ryhu
128GB last_kmsg (WITHOUT magisk): https://termbin.com/fub6

*512GB:*
512GB kmsg (with magisk): https://termbin.com/azeo
512GB last_kmsg (with magisk): https://termbin.com/blb9
512GB kmsg (WITHOUT magisk): https://termbin.com/k6vk
512GB last_kmsg (WITHOUT magisk): https://termbin.com/0tmu

**Comment by cawilliamson** [comment]
Ok, figured this one out:

```
--- a/arch/arm64/configs/exynos9810-crownlte_defconfig
+++ b/arch/arm64/configs/exynos9810-crownlte_defconfig
@@ -600,7 +600,7 @@
 # CONFIG_TIMA_LKMAUTH is not set
 # CONFIG_TIMA_LKM_BLOCK is not set
 # CONFIG_TIMA_LKMAUTH_CODE_PROT is not set
-CONFIG_UH=y
+# CONFIG_UH is not set
 # CONFIG_UH_DEBUG is not set
 # CONFIG_UH_RKP is not set
 # CONFIG_UH_INFORM is not set
```

Apply this patch (i.e. kill off CONFIG_UH) and two things happen:

1.) This and any kernel built from it can boot without Magisk.
2.) This and any kernel built from it can boot on the 512GB Note 9.

**Comment by farovitus** [comment]
Hi there, sorry for the late reply as i've been very busy lately.

I'm happy that you fixed it, i will merge your PR soon. We do not need CONFIG_UH anyway.
